---
name: Python Hello World Workflow
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print hello msg!
        run: echo "hello Python World in Github action"
